name: Convert Markdown to PDF and Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          fonts-noto-cjk \
          fonts-noto-cjk-extra

      - name: Install dependencies
        run: |
          npm install -g @marp-team/marp-cli

      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          for file in markdown/*.md; do
            filename=$(basename "$file" .md)
            marp "$file" --pdf --allow-local-files --theme markdown/theme.css -o "pdfs/${filename}.pdf"
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: v${{ github.run_number }}
          files: |
            pdfs/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
